version: "3.8"

services:
  postgres:
    image: postgres:13.20-alpine3.20 
    container_name: loyalty_postgres
    env_file:
      - .env  
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Optional: Preload tables

volumes:
  postgres_data: